# Real World Databases in series

## Basics

In [2]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    "Name": ["A", "B"],
    "Age": [20, 21],
    "City": ["Delhi", "Jaipur"]
})
df

  Name  Age    City
0    A   20   Delhi
1    B   21  Jaipur

In [10]:
df['City']

0     Delhi
1    Jaipur
Name: City, dtype: str

In [5]:
df[['City']]

     City
0   Delhi
1  Jaipur

In [8]:
df[["City", "Name"]]

     City Name
0   Delhi    A
1  Jaipur    B

In [11]:
import pandas as pd
import numpy as np

marks = pd.Series([85, np.nan, 90, np.nan, 78])

In [19]:
marks.isna() #isna = is + NA

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [20]:
marks.isna().sum()

np.int64(2)

In [22]:
marks.notna() # notna = not + NA

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [23]:
marks.sum()

np.float64(253.0)

In [25]:
marks.count() # It will count valid values and will ignore empty values

np.int64(3)

In [27]:
marks.mean() # Mean will calculated on valid values only eg. 3 here

np.float64(84.33333333333333)

In [28]:
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Aman"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 88]
})

In [31]:
df['Marks'].sum()

np.int64(263)

## DataFrames Attributes

In [33]:
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Aman"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 88]
})

In [34]:
df.shape

(3, 3)

In [35]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [36]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [37]:
df.dtypes

Name       str
Age      int64
Marks    int64
dtype: object

In [42]:
df.head(2) # head() returns rows from the top instead of full dataframe

    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90

In [41]:
df.tail(1) # tail() returns rows from the bottom

   Name  Age  Marks
2  Aman   19     88

In [45]:
df.head(100) # if the input value is more than rows than it will return the available number of rows same for tail()

    Name  Age  Marks
0  Rahul   20     85
1  Priya   21     90
2   Aman   19     88

In [53]:
df.sample(2) # sample() returns random rows

    Name  Age  Marks
0  Rahul   20     85
2   Aman   19     88

In [56]:
df.describe() 

#df.describe()
# Answers different questions:

# What's the average?
# What's the minimum?
# What's the maximum?
# What's the standard deviation?
# What are the quartiles (25%, 50%, 75%)?

# It's the statistical summary of your numeric columns

        Age      Marks
count   3.0   3.000000
mean   20.0  87.666667
std     1.0   2.516611
min    19.0  85.000000
25%    19.5  86.500000
50%    20.0  88.000000
75%    20.5  89.000000
max    21.0  90.000000

In [57]:
df.info()

# df.info()

# Answers questions like:

# How many rows are there?
# How many columns are there?
# What are the column names?
# What is the data type of each column?
# How many non-null (non-missing) values does each column have?
# How much memory is being used?

# It's basically the identity card of your DataFrame.

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [61]:
df.rename(columns={"Marks": "Score"}) # Returns a nnew data frame with new column name

    Name  Age  Score
0  Rahul   20     85
1  Priya   21     90
2   Aman   19     88

In [63]:
df.rename(columns={"Age": "Student_Age"}, inplace=True) # Permanently changes the current data frame

In [71]:
df.set_index("Name") # Changes default index

       Student_Age  Score
Name
Rahul           20     85
Priya           21     90
Aman            19     88

In [74]:
df.reset_index()

   index   Name  Student_Age  Score
0      0  Rahul           20     85
1      1  Priya           21     90
2      2   Aman           19     88